export {default as Home} from "./home/Home.jsx"
export {default as Contact} from "./contact/Contact.jsx"
export {default as Admin} from "./admin/Admin.jsx"
export {default as NoPage} from "./noPage/NoPage.jsx"
export {default as Hosting} from "./hosting/Hosting.jsx"